// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package bpfnat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpfnat_legacy returns the embedded CollectionSpec for bpfnat_legacy.
func loadBpfnat_legacy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpfnat_legacyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfnat_legacy: %w", err)
	}

	return spec, err
}

// loadBpfnat_legacyObjects loads bpfnat_legacy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfnat_legacyObjects
//	*bpfnat_legacyPrograms
//	*bpfnat_legacyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfnat_legacyObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfnat_legacy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfnat_legacySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_legacySpecs struct {
	bpfnat_legacyProgramSpecs
	bpfnat_legacyMapSpecs
}

// bpfnat_legacySpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_legacyProgramSpecs struct {
	SandboxdBridgeIngressBpfnat *ebpf.ProgramSpec `ebpf:"sandboxd_bridge_ingress_bpfnat"`
	SandboxdEgressBpfnat        *ebpf.ProgramSpec `ebpf:"sandboxd_egress_bpfnat"`
	SandboxdIngressBpfnat       *ebpf.ProgramSpec `ebpf:"sandboxd_ingress_bpfnat"`
	SandboxdLocalIngressBpfnat  *ebpf.ProgramSpec `ebpf:"sandboxd_local_ingress_bpfnat"`
}

// bpfnat_legacyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_legacyMapSpecs struct {
	DNAT_RULES_MAP     *ebpf.MapSpec `ebpf:"DNAT_RULES_MAP"`
	EGRESS_POLICY_MAP  *ebpf.MapSpec `ebpf:"EGRESS_POLICY_MAP"`
	LOCAL_REDIRECT_MAP *ebpf.MapSpec `ebpf:"LOCAL_REDIRECT_MAP"`
	POD_PORT_MAP       *ebpf.MapSpec `ebpf:"POD_PORT_MAP"`
	SNAT_CONFIG_MAP    *ebpf.MapSpec `ebpf:"SNAT_CONFIG_MAP"`
	SNAT_MAPPING_IPV4  *ebpf.MapSpec `ebpf:"SNAT_MAPPING_IPV4"`
}

// bpfnat_legacyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_legacyObjects struct {
	bpfnat_legacyPrograms
	bpfnat_legacyMaps
}

func (o *bpfnat_legacyObjects) Close() error {
	return _Bpfnat_legacyClose(
		&o.bpfnat_legacyPrograms,
		&o.bpfnat_legacyMaps,
	)
}

// bpfnat_legacyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_legacyMaps struct {
	DNAT_RULES_MAP     *ebpf.Map `ebpf:"DNAT_RULES_MAP"`
	EGRESS_POLICY_MAP  *ebpf.Map `ebpf:"EGRESS_POLICY_MAP"`
	LOCAL_REDIRECT_MAP *ebpf.Map `ebpf:"LOCAL_REDIRECT_MAP"`
	POD_PORT_MAP       *ebpf.Map `ebpf:"POD_PORT_MAP"`
	SNAT_CONFIG_MAP    *ebpf.Map `ebpf:"SNAT_CONFIG_MAP"`
	SNAT_MAPPING_IPV4  *ebpf.Map `ebpf:"SNAT_MAPPING_IPV4"`
}

func (m *bpfnat_legacyMaps) Close() error {
	return _Bpfnat_legacyClose(
		m.DNAT_RULES_MAP,
		m.EGRESS_POLICY_MAP,
		m.LOCAL_REDIRECT_MAP,
		m.POD_PORT_MAP,
		m.SNAT_CONFIG_MAP,
		m.SNAT_MAPPING_IPV4,
	)
}

// bpfnat_legacyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_legacyObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_legacyPrograms struct {
	SandboxdBridgeIngressBpfnat *ebpf.Program `ebpf:"sandboxd_bridge_ingress_bpfnat"`
	SandboxdEgressBpfnat        *ebpf.Program `ebpf:"sandboxd_egress_bpfnat"`
	SandboxdIngressBpfnat       *ebpf.Program `ebpf:"sandboxd_ingress_bpfnat"`
	SandboxdLocalIngressBpfnat  *ebpf.Program `ebpf:"sandboxd_local_ingress_bpfnat"`
}

func (p *bpfnat_legacyPrograms) Close() error {
	return _Bpfnat_legacyClose(
		p.SandboxdBridgeIngressBpfnat,
		p.SandboxdEgressBpfnat,
		p.SandboxdIngressBpfnat,
		p.SandboxdLocalIngressBpfnat,
	)
}

func _Bpfnat_legacyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfnat_legacy_bpfel.o
var _Bpfnat_legacyBytes []byte
