// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64
// +build 386 amd64 amd64p32 arm arm64 mips64le mips64p32le mipsle ppc64le riscv64

package bpfnat

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpfnat_timer returns the embedded CollectionSpec for bpfnat_timer.
func loadBpfnat_timer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpfnat_timerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfnat_timer: %w", err)
	}

	return spec, err
}

// loadBpfnat_timerObjects loads bpfnat_timer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfnat_timerObjects
//	*bpfnat_timerPrograms
//	*bpfnat_timerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfnat_timerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfnat_timer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfnat_timerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_timerSpecs struct {
	bpfnat_timerProgramSpecs
	bpfnat_timerMapSpecs
}

// bpfnat_timerSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_timerProgramSpecs struct {
	SandboxdBridgeIngressBpfnat *ebpf.ProgramSpec `ebpf:"sandboxd_bridge_ingress_bpfnat"`
	SandboxdEgressBpfnat        *ebpf.ProgramSpec `ebpf:"sandboxd_egress_bpfnat"`
	SandboxdIngressBpfnat       *ebpf.ProgramSpec `ebpf:"sandboxd_ingress_bpfnat"`
	SandboxdLocalIngressBpfnat  *ebpf.ProgramSpec `ebpf:"sandboxd_local_ingress_bpfnat"`
}

// bpfnat_timerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfnat_timerMapSpecs struct {
	DNAT_RULES_MAP     *ebpf.MapSpec `ebpf:"DNAT_RULES_MAP"`
	EGRESS_POLICY_MAP  *ebpf.MapSpec `ebpf:"EGRESS_POLICY_MAP"`
	LOCAL_REDIRECT_MAP *ebpf.MapSpec `ebpf:"LOCAL_REDIRECT_MAP"`
	POD_PORT_MAP       *ebpf.MapSpec `ebpf:"POD_PORT_MAP"`
	SNAT_CONFIG_MAP    *ebpf.MapSpec `ebpf:"SNAT_CONFIG_MAP"`
	SNAT_MAPPING_IPV4  *ebpf.MapSpec `ebpf:"SNAT_MAPPING_IPV4"`
}

// bpfnat_timerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_timerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_timerObjects struct {
	bpfnat_timerPrograms
	bpfnat_timerMaps
}

func (o *bpfnat_timerObjects) Close() error {
	return _Bpfnat_timerClose(
		&o.bpfnat_timerPrograms,
		&o.bpfnat_timerMaps,
	)
}

// bpfnat_timerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_timerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_timerMaps struct {
	DNAT_RULES_MAP     *ebpf.Map `ebpf:"DNAT_RULES_MAP"`
	EGRESS_POLICY_MAP  *ebpf.Map `ebpf:"EGRESS_POLICY_MAP"`
	LOCAL_REDIRECT_MAP *ebpf.Map `ebpf:"LOCAL_REDIRECT_MAP"`
	POD_PORT_MAP       *ebpf.Map `ebpf:"POD_PORT_MAP"`
	SNAT_CONFIG_MAP    *ebpf.Map `ebpf:"SNAT_CONFIG_MAP"`
	SNAT_MAPPING_IPV4  *ebpf.Map `ebpf:"SNAT_MAPPING_IPV4"`
}

func (m *bpfnat_timerMaps) Close() error {
	return _Bpfnat_timerClose(
		m.DNAT_RULES_MAP,
		m.EGRESS_POLICY_MAP,
		m.LOCAL_REDIRECT_MAP,
		m.POD_PORT_MAP,
		m.SNAT_CONFIG_MAP,
		m.SNAT_MAPPING_IPV4,
	)
}

// bpfnat_timerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfnat_timerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfnat_timerPrograms struct {
	SandboxdBridgeIngressBpfnat *ebpf.Program `ebpf:"sandboxd_bridge_ingress_bpfnat"`
	SandboxdEgressBpfnat        *ebpf.Program `ebpf:"sandboxd_egress_bpfnat"`
	SandboxdIngressBpfnat       *ebpf.Program `ebpf:"sandboxd_ingress_bpfnat"`
	SandboxdLocalIngressBpfnat  *ebpf.Program `ebpf:"sandboxd_local_ingress_bpfnat"`
}

func (p *bpfnat_timerPrograms) Close() error {
	return _Bpfnat_timerClose(
		p.SandboxdBridgeIngressBpfnat,
		p.SandboxdEgressBpfnat,
		p.SandboxdIngressBpfnat,
		p.SandboxdLocalIngressBpfnat,
	)
}

func _Bpfnat_timerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfnat_timer_bpfel.o
var _Bpfnat_timerBytes []byte
