// Copyright (c) 2026 Ant Group Corporation.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/physicalstate/metadata.proto

package physicalstate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PhysicalPhase is sandboxd-private recovery coordination. Only committed
// sandboxes may be published through the runtime List API.
type PhysicalPhase int32

const (
	PhysicalPhase_PHYSICAL_PHASE_UNSPECIFIED PhysicalPhase = 0
	PhysicalPhase_PHYSICAL_PHASE_INTENT      PhysicalPhase = 1
	PhysicalPhase_PHYSICAL_PHASE_COMMITTED   PhysicalPhase = 2
)

// Enum value maps for PhysicalPhase.
var (
	PhysicalPhase_name = map[int32]string{
		0: "PHYSICAL_PHASE_UNSPECIFIED",
		1: "PHYSICAL_PHASE_INTENT",
		2: "PHYSICAL_PHASE_COMMITTED",
	}
	PhysicalPhase_value = map[string]int32{
		"PHYSICAL_PHASE_UNSPECIFIED": 0,
		"PHYSICAL_PHASE_INTENT":      1,
		"PHYSICAL_PHASE_COMMITTED":   2,
	}
)

func (x PhysicalPhase) Enum() *PhysicalPhase {
	p := new(PhysicalPhase)
	*p = x
	return p
}

func (x PhysicalPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhysicalPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_physicalstate_metadata_proto_enumTypes[0].Descriptor()
}

func (PhysicalPhase) Type() protoreflect.EnumType {
	return &file_internal_physicalstate_metadata_proto_enumTypes[0]
}

func (x PhysicalPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhysicalPhase.Descriptor instead.
func (PhysicalPhase) EnumDescriptor() ([]byte, []int) {
	return file_internal_physicalstate_metadata_proto_rawDescGZIP(), []int{0}
}

// SandboxMetadata is sandboxd's durable physical record. Field numbers and
// wire types intentionally match the historical runtime.v1.SandboxMetadata
// encoding so existing meta.pb files remain readable after this type moves
// out of the public runtime API.
type SandboxMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RuntimeHandler  string                 `protobuf:"bytes,3,opt,name=runtime_handler,json=runtimeHandler,proto3" json:"runtime_handler,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stdout          string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	MetricLabels    map[string]string      `protobuf:"bytes,8,rep,name=metric_labels,json=metricLabels,proto3" json:"metric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports           []string               `protobuf:"bytes,9,rep,name=ports,proto3" json:"ports,omitempty"`
	PhysicalPhase   PhysicalPhase          `protobuf:"varint,10,opt,name=physical_phase,json=physicalPhase,proto3,enum=sandboxd.internal.physicalstate.PhysicalPhase" json:"physical_phase,omitempty"`
	RestoreIdentity *RestoreIdentity       `protobuf:"bytes,11,opt,name=restore_identity,json=restoreIdentity,proto3" json:"restore_identity,omitempty"`
	ResourceFacts   map[string]string      `protobuf:"bytes,12,rep,name=resource_facts,json=resourceFacts,proto3" json:"resource_facts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SandboxMetadata) Reset() {
	*x = SandboxMetadata{}
	mi := &file_internal_physicalstate_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetadata) ProtoMessage() {}

func (x *SandboxMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_physicalstate_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxMetadata.ProtoReflect.Descriptor instead.
func (*SandboxMetadata) Descriptor() ([]byte, []int) {
	return file_internal_physicalstate_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SandboxMetadata) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *SandboxMetadata) GetRuntimeHandler() string {
	if x != nil {
		return x.RuntimeHandler
	}
	return ""
}

func (x *SandboxMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxMetadata) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *SandboxMetadata) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *SandboxMetadata) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

func (x *SandboxMetadata) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *SandboxMetadata) GetPhysicalPhase() PhysicalPhase {
	if x != nil {
		return x.PhysicalPhase
	}
	return PhysicalPhase_PHYSICAL_PHASE_UNSPECIFIED
}

func (x *SandboxMetadata) GetRestoreIdentity() *RestoreIdentity {
	if x != nil {
		return x.RestoreIdentity
	}
	return nil
}

func (x *SandboxMetadata) GetResourceFacts() map[string]string {
	if x != nil {
		return x.ResourceFacts
	}
	return nil
}

// RestoreIdentity binds a deterministic physical sandbox to one immutable
// checkpoint and normalized restore request.
type RestoreIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointID  string                 `protobuf:"bytes,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	RequestSha256 string                 `protobuf:"bytes,2,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreIdentity) Reset() {
	*x = RestoreIdentity{}
	mi := &file_internal_physicalstate_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreIdentity) ProtoMessage() {}

func (x *RestoreIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_physicalstate_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreIdentity.ProtoReflect.Descriptor instead.
func (*RestoreIdentity) Descriptor() ([]byte, []int) {
	return file_internal_physicalstate_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreIdentity) GetCheckpointID() string {
	if x != nil {
		return x.CheckpointID
	}
	return ""
}

func (x *RestoreIdentity) GetRequestSha256() string {
	if x != nil {
		return x.RequestSha256
	}
	return ""
}

var File_internal_physicalstate_metadata_proto protoreflect.FileDescriptor

const file_internal_physicalstate_metadata_proto_rawDesc = "" +
	"\n" +
	"%internal/physicalstate/metadata.proto\x12\x1fsandboxd.internal.physicalstate\"\xb9\x06\n" +
	"\x0fSandboxMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fruntime_handler\x18\x03 \x01(\tR\x0eruntimeHandler\x12T\n" +
	"\x06labels\x18\x04 \x03(\v2<.sandboxd.internal.physicalstate.SandboxMetadata.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12g\n" +
	"\rmetric_labels\x18\b \x03(\v2B.sandboxd.internal.physicalstate.SandboxMetadata.MetricLabelsEntryR\fmetricLabels\x12\x14\n" +
	"\x05ports\x18\t \x03(\tR\x05ports\x12U\n" +
	"\x0ephysical_phase\x18\n" +
	" \x01(\x0e2..sandboxd.internal.physicalstate.PhysicalPhaseR\rphysicalPhase\x12[\n" +
	"\x10restore_identity\x18\v \x01(\v20.sandboxd.internal.physicalstate.RestoreIdentityR\x0frestoreIdentity\x12j\n" +
	"\x0eresource_facts\x18\f \x03(\v2C.sandboxd.internal.physicalstate.SandboxMetadata.ResourceFactsEntryR\rresourceFacts\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12ResourceFactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03J\x04\b\x05\x10\x06\"]\n" +
	"\x0fRestoreIdentity\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\tR\fcheckpointId\x12%\n" +
	"\x0erequest_sha256\x18\x02 \x01(\tR\rrequestSha256*h\n" +
	"\rPhysicalPhase\x12\x1e\n" +
	"\x1aPHYSICAL_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PHYSICAL_PHASE_INTENT\x10\x01\x12\x1c\n" +
	"\x18PHYSICAL_PHASE_COMMITTED\x10\x02B8Z6github.com/inclusionAI/sandboxd/internal/physicalstateb\x06proto3"

var (
	file_internal_physicalstate_metadata_proto_rawDescOnce sync.Once
	file_internal_physicalstate_metadata_proto_rawDescData []byte
)

func file_internal_physicalstate_metadata_proto_rawDescGZIP() []byte {
	file_internal_physicalstate_metadata_proto_rawDescOnce.Do(func() {
		file_internal_physicalstate_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_physicalstate_metadata_proto_rawDesc), len(file_internal_physicalstate_metadata_proto_rawDesc)))
	})
	return file_internal_physicalstate_metadata_proto_rawDescData
}

var file_internal_physicalstate_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_physicalstate_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_physicalstate_metadata_proto_goTypes = []any{
	(PhysicalPhase)(0),      // 0: sandboxd.internal.physicalstate.PhysicalPhase
	(*SandboxMetadata)(nil), // 1: sandboxd.internal.physicalstate.SandboxMetadata
	(*RestoreIdentity)(nil), // 2: sandboxd.internal.physicalstate.RestoreIdentity
	nil,                     // 3: sandboxd.internal.physicalstate.SandboxMetadata.LabelsEntry
	nil,                     // 4: sandboxd.internal.physicalstate.SandboxMetadata.MetricLabelsEntry
	nil,                     // 5: sandboxd.internal.physicalstate.SandboxMetadata.ResourceFactsEntry
}
var file_internal_physicalstate_metadata_proto_depIdxs = []int32{
	3, // 0: sandboxd.internal.physicalstate.SandboxMetadata.labels:type_name -> sandboxd.internal.physicalstate.SandboxMetadata.LabelsEntry
	4, // 1: sandboxd.internal.physicalstate.SandboxMetadata.metric_labels:type_name -> sandboxd.internal.physicalstate.SandboxMetadata.MetricLabelsEntry
	0, // 2: sandboxd.internal.physicalstate.SandboxMetadata.physical_phase:type_name -> sandboxd.internal.physicalstate.PhysicalPhase
	2, // 3: sandboxd.internal.physicalstate.SandboxMetadata.restore_identity:type_name -> sandboxd.internal.physicalstate.RestoreIdentity
	5, // 4: sandboxd.internal.physicalstate.SandboxMetadata.resource_facts:type_name -> sandboxd.internal.physicalstate.SandboxMetadata.ResourceFactsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_physicalstate_metadata_proto_init() }
func file_internal_physicalstate_metadata_proto_init() {
	if File_internal_physicalstate_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_physicalstate_metadata_proto_rawDesc), len(file_internal_physicalstate_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_physicalstate_metadata_proto_goTypes,
		DependencyIndexes: file_internal_physicalstate_metadata_proto_depIdxs,
		EnumInfos:         file_internal_physicalstate_metadata_proto_enumTypes,
		MessageInfos:      file_internal_physicalstate_metadata_proto_msgTypes,
	}.Build()
	File_internal_physicalstate_metadata_proto = out.File
	file_internal_physicalstate_metadata_proto_goTypes = nil
	file_internal_physicalstate_metadata_proto_depIdxs = nil
}
